default: &default
  adapter: postgresql
  encoding: utf8
  max_connections: 5
  username: minh
  password:

development:
  <<: *default
  database: buildcauhinh_development

test:
  <<: *default
  database: buildcauhinh_test

production:
  <<: *default
  database: buildcauhinh_production
  username: <%= ENV['BUILDCAUHINH_DATABASE_USERNAME'] %>
  password: <%= ENV['BUILDCAUHINH_DATABASE_PASSWORD'] %>
  max_connections: <%= ENV['BUILDCAUHINH_MAX_THREAD'] %>
